honeypot:
  name: "honeygotchi"
  version: "1.0.0"
  
# SSH Server settings
ssh:
  host: "0.0.0.0"
  port: 2222
  key_path: "config/server.key"
  banner: "SSH-2.0-OpenSSH_8.9p1"
  
# Reinforcement Learning settings
rl:
  model_dir: "rl_agent/policies"
  epsilon: 0.1
  save_interval: 10s
  
# User Interface settings
ui:
  # Terminal UI
  terminal: true
  
  # Web UI
  web: true
  web_host: "0.0.0.0"
  web_port: 8080
  
# Logging configuration
logging:
  level: "INFO"
  file: "logs/honeypot.log"
  rotate: true
  max_size: 10485760  # 10MB
  backups: 5